#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
SCRIPT_DIR="scripts"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Running MacOS setup"
    sh "${BASEDIR}/${SCRIPT_DIR}/set-macos-defaults.sh"
    sh "${BASEDIR}/${SCRIPT_DIR}/install-dependencies-macos.sh"
    echo "Installing Fonts"
    sh "${BASEDIR}/${SCRIPT_DIR}/install-fonts-macos.sh"
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
